on:
  push:
    branches:
      - master
jobs:
  js:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Clone Repository (common)
        uses: actions/checkout@v2
        with:
          repository: cheatank/common
          path: common
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle
      - name: Build common
        working-directory: common
        run: ./gradlew publishToMavenLocal
      - name: Build js
        run: ./gradlew jsBrowserProductionWebpack
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/distributions
